// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apbtvagnlkuwjzmsntit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwYnR2YWdubGt1d2p6bXNudGl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTkwMjAsImV4cCI6MjA2NTU5NTAyMH0.he5JV0liRErYja0HyYWWkqzPUrocqNYqHTU9oN61zh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);